name: Deploy to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Use Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Build
        run: |
          yarn install
          yarn build

      - name: Upload Built Files
        uses: actions/upload-pages-artifact@v5
        with:
          path: dist/

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v5
